
[terminal.shell]
program = "zellij"

[window]
padding = { x = 12, y = 12 }
opacity = 0.95

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[general]
import = [
    "~/.config/alacritty/themes/solarized_dark.toml"
]

[terminal]
